/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomCabinetryCalgaryRouteImport } from './routes/custom-cabinetry-calgary'
import { Route as CustomCabinetryCharlottetownRouteImport } from './routes/custom-cabinetry-charlottetown'
import { Route as CustomCabinetryEdmontonRouteImport } from './routes/custom-cabinetry-edmonton'
import { Route as CustomCabinetryFrederictonRouteImport } from './routes/custom-cabinetry-fredericton'
import { Route as CustomCabinetryHalifaxRouteImport } from './routes/custom-cabinetry-halifax'
import { Route as CustomCabinetryHamiltonRouteImport } from './routes/custom-cabinetry-hamilton'
import { Route as CustomCabinetryKitchenerRouteImport } from './routes/custom-cabinetry-kitchener'
import { Route as CustomCabinetryMonctonRouteImport } from './routes/custom-cabinetry-moncton'
import { Route as CustomCabinetryMontrealRouteImport } from './routes/custom-cabinetry-montreal'
import { Route as CustomCabinetryOttawaRouteImport } from './routes/custom-cabinetry-ottawa'
import { Route as CustomCabinetryQuebecCityRouteImport } from './routes/custom-cabinetry-quebec-city'
import { Route as CustomCabinetrySaintJohnRouteImport } from './routes/custom-cabinetry-saint-john'
import { Route as CustomCabinetryStJohnsRouteImport } from './routes/custom-cabinetry-st-johns'
import { Route as CustomCabinetryTorontoRouteImport } from './routes/custom-cabinetry-toronto'
import { Route as CustomCabinetryVancouverRouteImport } from './routes/custom-cabinetry-vancouver'
import { Route as CustomCabinetryWinnipegRouteImport } from './routes/custom-cabinetry-winnipeg'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as RushCustomKitchenCabinetsRouteImport } from './routes/rush-custom-kitchen-cabinets'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapImagesDotxmlRouteImport } from './routes/sitemap-images[.]xml'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WorkWithUsRouteImport } from './routes/work-with-us'
import { Route as ProductsBrandsRouteImport } from './routes/products.brands'
import { Route as ProductsCabinetStylesRouteImport } from './routes/products.cabinet-styles'
import { Route as ProductsColoursFinishesRouteImport } from './routes/products.colours-finishes'
import { Route as ProductsDoorStylesRouteImport } from './routes/products.door-styles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomCabinetryCalgaryRoute = CustomCabinetryCalgaryRouteImport.update({
  id: '/custom-cabinetry-calgary',
  path: '/custom-cabinetry-calgary',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomCabinetryCharlottetownRoute =
  CustomCabinetryCharlottetownRouteImport.update({
    id: '/custom-cabinetry-charlottetown',
    path: '/custom-cabinetry-charlottetown',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomCabinetryEdmontonRoute = CustomCabinetryEdmontonRouteImport.update({
  id: '/custom-cabinetry-edmonton',
  path: '/custom-cabinetry-edmonton',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomCabinetryFrederictonRoute =
  CustomCabinetryFrederictonRouteImport.update({
    id: '/custom-cabinetry-fredericton',
    path: '/custom-cabinetry-fredericton',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomCabinetryHalifaxRoute = CustomCabinetryHalifaxRouteImport.update({
  id: '/custom-cabinetry-halifax',
  path: '/custom-cabinetry-halifax',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomCabinetryHamiltonRoute = CustomCabinetryHamiltonRouteImport.update({
  id: '/custom-cabinetry-hamilton',
  path: '/custom-cabinetry-hamilton',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomCabinetryKitchenerRoute =
  CustomCabinetryKitchenerRouteImport.update({
    id: '/custom-cabinetry-kitchener',
    path: '/custom-cabinetry-kitchener',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomCabinetryMonctonRoute = CustomCabinetryMonctonRouteImport.update({
  id: '/custom-cabinetry-moncton',
  path: '/custom-cabinetry-moncton',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomCabinetryMontrealRoute = CustomCabinetryMontrealRouteImport.update({
  id: '/custom-cabinetry-montreal',
  path: '/custom-cabinetry-montreal',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomCabinetryOttawaRoute = CustomCabinetryOttawaRouteImport.update({
  id: '/custom-cabinetry-ottawa',
  path: '/custom-cabinetry-ottawa',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomCabinetryQuebecCityRoute =
  CustomCabinetryQuebecCityRouteImport.update({
    id: '/custom-cabinetry-quebec-city',
    path: '/custom-cabinetry-quebec-city',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomCabinetrySaintJohnRoute =
  CustomCabinetrySaintJohnRouteImport.update({
    id: '/custom-cabinetry-saint-john',
    path: '/custom-cabinetry-saint-john',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomCabinetryStJohnsRoute = CustomCabinetryStJohnsRouteImport.update({
  id: '/custom-cabinetry-st-johns',
  path: '/custom-cabinetry-st-johns',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomCabinetryTorontoRoute = CustomCabinetryTorontoRouteImport.update({
  id: '/custom-cabinetry-toronto',
  path: '/custom-cabinetry-toronto',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomCabinetryVancouverRoute =
  CustomCabinetryVancouverRouteImport.update({
    id: '/custom-cabinetry-vancouver',
    path: '/custom-cabinetry-vancouver',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomCabinetryWinnipegRoute = CustomCabinetryWinnipegRouteImport.update({
  id: '/custom-cabinetry-winnipeg',
  path: '/custom-cabinetry-winnipeg',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const RushCustomKitchenCabinetsRoute =
  RushCustomKitchenCabinetsRouteImport.update({
    id: '/rush-custom-kitchen-cabinets',
    path: '/rush-custom-kitchen-cabinets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapImagesDotxmlRoute = SitemapImagesDotxmlRouteImport.update({
  id: '/sitemap-images.xml',
  path: '/sitemap-images.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkWithUsRoute = WorkWithUsRouteImport.update({
  id: '/work-with-us',
  path: '/work-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsBrandsRoute = ProductsBrandsRouteImport.update({
  id: '/products/brands',
  path: '/products/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCabinetStylesRoute = ProductsCabinetStylesRouteImport.update({
  id: '/products/cabinet-styles',
  path: '/products/cabinet-styles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsColoursFinishesRoute = ProductsColoursFinishesRouteImport.update({
  id: '/products/colours-finishes',
  path: '/products/colours-finishes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsDoorStylesRoute = ProductsDoorStylesRouteImport.update({
  id: '/products/door-styles',
  path: '/products/door-styles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/custom-cabinetry-calgary': typeof CustomCabinetryCalgaryRoute
  '/custom-cabinetry-charlottetown': typeof CustomCabinetryCharlottetownRoute
  '/custom-cabinetry-edmonton': typeof CustomCabinetryEdmontonRoute
  '/custom-cabinetry-fredericton': typeof CustomCabinetryFrederictonRoute
  '/custom-cabinetry-halifax': typeof CustomCabinetryHalifaxRoute
  '/custom-cabinetry-hamilton': typeof CustomCabinetryHamiltonRoute
  '/custom-cabinetry-kitchener': typeof CustomCabinetryKitchenerRoute
  '/custom-cabinetry-moncton': typeof CustomCabinetryMonctonRoute
  '/custom-cabinetry-montreal': typeof CustomCabinetryMontrealRoute
  '/custom-cabinetry-ottawa': typeof CustomCabinetryOttawaRoute
  '/custom-cabinetry-quebec-city': typeof CustomCabinetryQuebecCityRoute
  '/custom-cabinetry-saint-john': typeof CustomCabinetrySaintJohnRoute
  '/custom-cabinetry-st-johns': typeof CustomCabinetryStJohnsRoute
  '/custom-cabinetry-toronto': typeof CustomCabinetryTorontoRoute
  '/custom-cabinetry-vancouver': typeof CustomCabinetryVancouverRoute
  '/custom-cabinetry-winnipeg': typeof CustomCabinetryWinnipegRoute
  '/locations': typeof LocationsRoute
  '/rush-custom-kitchen-cabinets': typeof RushCustomKitchenCabinetsRoute
  '/services': typeof ServicesRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/products/brands': typeof ProductsBrandsRoute
  '/products/cabinet-styles': typeof ProductsCabinetStylesRoute
  '/products/colours-finishes': typeof ProductsColoursFinishesRoute
  '/products/door-styles': typeof ProductsDoorStylesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/custom-cabinetry-calgary': typeof CustomCabinetryCalgaryRoute
  '/custom-cabinetry-charlottetown': typeof CustomCabinetryCharlottetownRoute
  '/custom-cabinetry-edmonton': typeof CustomCabinetryEdmontonRoute
  '/custom-cabinetry-fredericton': typeof CustomCabinetryFrederictonRoute
  '/custom-cabinetry-halifax': typeof CustomCabinetryHalifaxRoute
  '/custom-cabinetry-hamilton': typeof CustomCabinetryHamiltonRoute
  '/custom-cabinetry-kitchener': typeof CustomCabinetryKitchenerRoute
  '/custom-cabinetry-moncton': typeof CustomCabinetryMonctonRoute
  '/custom-cabinetry-montreal': typeof CustomCabinetryMontrealRoute
  '/custom-cabinetry-ottawa': typeof CustomCabinetryOttawaRoute
  '/custom-cabinetry-quebec-city': typeof CustomCabinetryQuebecCityRoute
  '/custom-cabinetry-saint-john': typeof CustomCabinetrySaintJohnRoute
  '/custom-cabinetry-st-johns': typeof CustomCabinetryStJohnsRoute
  '/custom-cabinetry-toronto': typeof CustomCabinetryTorontoRoute
  '/custom-cabinetry-vancouver': typeof CustomCabinetryVancouverRoute
  '/custom-cabinetry-winnipeg': typeof CustomCabinetryWinnipegRoute
  '/locations': typeof LocationsRoute
  '/rush-custom-kitchen-cabinets': typeof RushCustomKitchenCabinetsRoute
  '/services': typeof ServicesRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/products/brands': typeof ProductsBrandsRoute
  '/products/cabinet-styles': typeof ProductsCabinetStylesRoute
  '/products/colours-finishes': typeof ProductsColoursFinishesRoute
  '/products/door-styles': typeof ProductsDoorStylesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/custom-cabinetry-calgary': typeof CustomCabinetryCalgaryRoute
  '/custom-cabinetry-charlottetown': typeof CustomCabinetryCharlottetownRoute
  '/custom-cabinetry-edmonton': typeof CustomCabinetryEdmontonRoute
  '/custom-cabinetry-fredericton': typeof CustomCabinetryFrederictonRoute
  '/custom-cabinetry-halifax': typeof CustomCabinetryHalifaxRoute
  '/custom-cabinetry-hamilton': typeof CustomCabinetryHamiltonRoute
  '/custom-cabinetry-kitchener': typeof CustomCabinetryKitchenerRoute
  '/custom-cabinetry-moncton': typeof CustomCabinetryMonctonRoute
  '/custom-cabinetry-montreal': typeof CustomCabinetryMontrealRoute
  '/custom-cabinetry-ottawa': typeof CustomCabinetryOttawaRoute
  '/custom-cabinetry-quebec-city': typeof CustomCabinetryQuebecCityRoute
  '/custom-cabinetry-saint-john': typeof CustomCabinetrySaintJohnRoute
  '/custom-cabinetry-st-johns': typeof CustomCabinetryStJohnsRoute
  '/custom-cabinetry-toronto': typeof CustomCabinetryTorontoRoute
  '/custom-cabinetry-vancouver': typeof CustomCabinetryVancouverRoute
  '/custom-cabinetry-winnipeg': typeof CustomCabinetryWinnipegRoute
  '/locations': typeof LocationsRoute
  '/rush-custom-kitchen-cabinets': typeof RushCustomKitchenCabinetsRoute
  '/services': typeof ServicesRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/products/brands': typeof ProductsBrandsRoute
  '/products/cabinet-styles': typeof ProductsCabinetStylesRoute
  '/products/colours-finishes': typeof ProductsColoursFinishesRoute
  '/products/door-styles': typeof ProductsDoorStylesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/custom-cabinetry-calgary'
    | '/custom-cabinetry-charlottetown'
    | '/custom-cabinetry-edmonton'
    | '/custom-cabinetry-fredericton'
    | '/custom-cabinetry-halifax'
    | '/custom-cabinetry-hamilton'
    | '/custom-cabinetry-kitchener'
    | '/custom-cabinetry-moncton'
    | '/custom-cabinetry-montreal'
    | '/custom-cabinetry-ottawa'
    | '/custom-cabinetry-quebec-city'
    | '/custom-cabinetry-saint-john'
    | '/custom-cabinetry-st-johns'
    | '/custom-cabinetry-toronto'
    | '/custom-cabinetry-vancouver'
    | '/custom-cabinetry-winnipeg'
    | '/locations'
    | '/rush-custom-kitchen-cabinets'
    | '/services'
    | '/sitemap-images.xml'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/work-with-us'
    | '/products/brands'
    | '/products/cabinet-styles'
    | '/products/colours-finishes'
    | '/products/door-styles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/custom-cabinetry-calgary'
    | '/custom-cabinetry-charlottetown'
    | '/custom-cabinetry-edmonton'
    | '/custom-cabinetry-fredericton'
    | '/custom-cabinetry-halifax'
    | '/custom-cabinetry-hamilton'
    | '/custom-cabinetry-kitchener'
    | '/custom-cabinetry-moncton'
    | '/custom-cabinetry-montreal'
    | '/custom-cabinetry-ottawa'
    | '/custom-cabinetry-quebec-city'
    | '/custom-cabinetry-saint-john'
    | '/custom-cabinetry-st-johns'
    | '/custom-cabinetry-toronto'
    | '/custom-cabinetry-vancouver'
    | '/custom-cabinetry-winnipeg'
    | '/locations'
    | '/rush-custom-kitchen-cabinets'
    | '/services'
    | '/sitemap-images.xml'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/work-with-us'
    | '/products/brands'
    | '/products/cabinet-styles'
    | '/products/colours-finishes'
    | '/products/door-styles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/custom-cabinetry-calgary'
    | '/custom-cabinetry-charlottetown'
    | '/custom-cabinetry-edmonton'
    | '/custom-cabinetry-fredericton'
    | '/custom-cabinetry-halifax'
    | '/custom-cabinetry-hamilton'
    | '/custom-cabinetry-kitchener'
    | '/custom-cabinetry-moncton'
    | '/custom-cabinetry-montreal'
    | '/custom-cabinetry-ottawa'
    | '/custom-cabinetry-quebec-city'
    | '/custom-cabinetry-saint-john'
    | '/custom-cabinetry-st-johns'
    | '/custom-cabinetry-toronto'
    | '/custom-cabinetry-vancouver'
    | '/custom-cabinetry-winnipeg'
    | '/locations'
    | '/rush-custom-kitchen-cabinets'
    | '/services'
    | '/sitemap-images.xml'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/work-with-us'
    | '/products/brands'
    | '/products/cabinet-styles'
    | '/products/colours-finishes'
    | '/products/door-styles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  CustomCabinetryCalgaryRoute: typeof CustomCabinetryCalgaryRoute
  CustomCabinetryCharlottetownRoute: typeof CustomCabinetryCharlottetownRoute
  CustomCabinetryEdmontonRoute: typeof CustomCabinetryEdmontonRoute
  CustomCabinetryFrederictonRoute: typeof CustomCabinetryFrederictonRoute
  CustomCabinetryHalifaxRoute: typeof CustomCabinetryHalifaxRoute
  CustomCabinetryHamiltonRoute: typeof CustomCabinetryHamiltonRoute
  CustomCabinetryKitchenerRoute: typeof CustomCabinetryKitchenerRoute
  CustomCabinetryMonctonRoute: typeof CustomCabinetryMonctonRoute
  CustomCabinetryMontrealRoute: typeof CustomCabinetryMontrealRoute
  CustomCabinetryOttawaRoute: typeof CustomCabinetryOttawaRoute
  CustomCabinetryQuebecCityRoute: typeof CustomCabinetryQuebecCityRoute
  CustomCabinetrySaintJohnRoute: typeof CustomCabinetrySaintJohnRoute
  CustomCabinetryStJohnsRoute: typeof CustomCabinetryStJohnsRoute
  CustomCabinetryTorontoRoute: typeof CustomCabinetryTorontoRoute
  CustomCabinetryVancouverRoute: typeof CustomCabinetryVancouverRoute
  CustomCabinetryWinnipegRoute: typeof CustomCabinetryWinnipegRoute
  LocationsRoute: typeof LocationsRoute
  RushCustomKitchenCabinetsRoute: typeof RushCustomKitchenCabinetsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapImagesDotxmlRoute: typeof SitemapImagesDotxmlRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkWithUsRoute: typeof WorkWithUsRoute
  ProductsBrandsRoute: typeof ProductsBrandsRoute
  ProductsCabinetStylesRoute: typeof ProductsCabinetStylesRoute
  ProductsColoursFinishesRoute: typeof ProductsColoursFinishesRoute
  ProductsDoorStylesRoute: typeof ProductsDoorStylesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cabinetry-calgary': {
      id: '/custom-cabinetry-calgary'
      path: '/custom-cabinetry-calgary'
      fullPath: '/custom-cabinetry-calgary'
      preLoaderRoute: typeof CustomCabinetryCalgaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cabinetry-charlottetown': {
      id: '/custom-cabinetry-charlottetown'
      path: '/custom-cabinetry-charlottetown'
      fullPath: '/custom-cabinetry-charlottetown'
      preLoaderRoute: typeof CustomCabinetryCharlottetownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cabinetry-edmonton': {
      id: '/custom-cabinetry-edmonton'
      path: '/custom-cabinetry-edmonton'
      fullPath: '/custom-cabinetry-edmonton'
      preLoaderRoute: typeof CustomCabinetryEdmontonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cabinetry-fredericton': {
      id: '/custom-cabinetry-fredericton'
      path: '/custom-cabinetry-fredericton'
      fullPath: '/custom-cabinetry-fredericton'
      preLoaderRoute: typeof CustomCabinetryFrederictonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cabinetry-halifax': {
      id: '/custom-cabinetry-halifax'
      path: '/custom-cabinetry-halifax'
      fullPath: '/custom-cabinetry-halifax'
      preLoaderRoute: typeof CustomCabinetryHalifaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cabinetry-hamilton': {
      id: '/custom-cabinetry-hamilton'
      path: '/custom-cabinetry-hamilton'
      fullPath: '/custom-cabinetry-hamilton'
      preLoaderRoute: typeof CustomCabinetryHamiltonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cabinetry-kitchener': {
      id: '/custom-cabinetry-kitchener'
      path: '/custom-cabinetry-kitchener'
      fullPath: '/custom-cabinetry-kitchener'
      preLoaderRoute: typeof CustomCabinetryKitchenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cabinetry-moncton': {
      id: '/custom-cabinetry-moncton'
      path: '/custom-cabinetry-moncton'
      fullPath: '/custom-cabinetry-moncton'
      preLoaderRoute: typeof CustomCabinetryMonctonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cabinetry-montreal': {
      id: '/custom-cabinetry-montreal'
      path: '/custom-cabinetry-montreal'
      fullPath: '/custom-cabinetry-montreal'
      preLoaderRoute: typeof CustomCabinetryMontrealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cabinetry-ottawa': {
      id: '/custom-cabinetry-ottawa'
      path: '/custom-cabinetry-ottawa'
      fullPath: '/custom-cabinetry-ottawa'
      preLoaderRoute: typeof CustomCabinetryOttawaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cabinetry-quebec-city': {
      id: '/custom-cabinetry-quebec-city'
      path: '/custom-cabinetry-quebec-city'
      fullPath: '/custom-cabinetry-quebec-city'
      preLoaderRoute: typeof CustomCabinetryQuebecCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cabinetry-saint-john': {
      id: '/custom-cabinetry-saint-john'
      path: '/custom-cabinetry-saint-john'
      fullPath: '/custom-cabinetry-saint-john'
      preLoaderRoute: typeof CustomCabinetrySaintJohnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cabinetry-st-johns': {
      id: '/custom-cabinetry-st-johns'
      path: '/custom-cabinetry-st-johns'
      fullPath: '/custom-cabinetry-st-johns'
      preLoaderRoute: typeof CustomCabinetryStJohnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cabinetry-toronto': {
      id: '/custom-cabinetry-toronto'
      path: '/custom-cabinetry-toronto'
      fullPath: '/custom-cabinetry-toronto'
      preLoaderRoute: typeof CustomCabinetryTorontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cabinetry-vancouver': {
      id: '/custom-cabinetry-vancouver'
      path: '/custom-cabinetry-vancouver'
      fullPath: '/custom-cabinetry-vancouver'
      preLoaderRoute: typeof CustomCabinetryVancouverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cabinetry-winnipeg': {
      id: '/custom-cabinetry-winnipeg'
      path: '/custom-cabinetry-winnipeg'
      fullPath: '/custom-cabinetry-winnipeg'
      preLoaderRoute: typeof CustomCabinetryWinnipegRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rush-custom-kitchen-cabinets': {
      id: '/rush-custom-kitchen-cabinets'
      path: '/rush-custom-kitchen-cabinets'
      fullPath: '/rush-custom-kitchen-cabinets'
      preLoaderRoute: typeof RushCustomKitchenCabinetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-images.xml': {
      id: '/sitemap-images.xml'
      path: '/sitemap-images.xml'
      fullPath: '/sitemap-images.xml'
      preLoaderRoute: typeof SitemapImagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-with-us': {
      id: '/work-with-us'
      path: '/work-with-us'
      fullPath: '/work-with-us'
      preLoaderRoute: typeof WorkWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/brands': {
      id: '/products/brands'
      path: '/products/brands'
      fullPath: '/products/brands'
      preLoaderRoute: typeof ProductsBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/cabinet-styles': {
      id: '/products/cabinet-styles'
      path: '/products/cabinet-styles'
      fullPath: '/products/cabinet-styles'
      preLoaderRoute: typeof ProductsCabinetStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/colours-finishes': {
      id: '/products/colours-finishes'
      path: '/products/colours-finishes'
      fullPath: '/products/colours-finishes'
      preLoaderRoute: typeof ProductsColoursFinishesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/door-styles': {
      id: '/products/door-styles'
      path: '/products/door-styles'
      fullPath: '/products/door-styles'
      preLoaderRoute: typeof ProductsDoorStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  CustomCabinetryCalgaryRoute: CustomCabinetryCalgaryRoute,
  CustomCabinetryCharlottetownRoute: CustomCabinetryCharlottetownRoute,
  CustomCabinetryEdmontonRoute: CustomCabinetryEdmontonRoute,
  CustomCabinetryFrederictonRoute: CustomCabinetryFrederictonRoute,
  CustomCabinetryHalifaxRoute: CustomCabinetryHalifaxRoute,
  CustomCabinetryHamiltonRoute: CustomCabinetryHamiltonRoute,
  CustomCabinetryKitchenerRoute: CustomCabinetryKitchenerRoute,
  CustomCabinetryMonctonRoute: CustomCabinetryMonctonRoute,
  CustomCabinetryMontrealRoute: CustomCabinetryMontrealRoute,
  CustomCabinetryOttawaRoute: CustomCabinetryOttawaRoute,
  CustomCabinetryQuebecCityRoute: CustomCabinetryQuebecCityRoute,
  CustomCabinetrySaintJohnRoute: CustomCabinetrySaintJohnRoute,
  CustomCabinetryStJohnsRoute: CustomCabinetryStJohnsRoute,
  CustomCabinetryTorontoRoute: CustomCabinetryTorontoRoute,
  CustomCabinetryVancouverRoute: CustomCabinetryVancouverRoute,
  CustomCabinetryWinnipegRoute: CustomCabinetryWinnipegRoute,
  LocationsRoute: LocationsRoute,
  RushCustomKitchenCabinetsRoute: RushCustomKitchenCabinetsRoute,
  ServicesRoute: ServicesRoute,
  SitemapImagesDotxmlRoute: SitemapImagesDotxmlRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkWithUsRoute: WorkWithUsRoute,
  ProductsBrandsRoute: ProductsBrandsRoute,
  ProductsCabinetStylesRoute: ProductsCabinetStylesRoute,
  ProductsColoursFinishesRoute: ProductsColoursFinishesRoute,
  ProductsDoorStylesRoute: ProductsDoorStylesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
